const genres = [
    { slug: '/moi-cap-nhat', label: 'Mới cập nhật', icon: '⚡', bg: 'green' },
    { slug: '/truyen-moi', label: 'Truyện mới', icon: '✌', bg: 'yellow' },
    { slug: '/random-truyen', label: 'Random truyện', icon: '🔥', bg: 'purple' },
    { slug: '/hoan-thanh', label: 'Hoàn thành', icon: '✅', bg: 'blue' },
    { slug: '/genre/action-95', label: 'Action' },
    { slug: '/genre/truong-thanh', label: 'Adult' },
    { slug: '/genre/adventure', label: 'Adventure' },
    { slug: '/genre/anime', label: 'Anime' },
    { slug: '/genre/chuyen-sinh-2131', label: 'Chuyển Sinh' },
    { slug: '/genre/comedy-99', label: 'Comedy' },
    { slug: '/genre/comic', label: 'Comic' },
    { slug: '/genre/cooking', label: 'Cooking' },
    { slug: '/genre/co-dai-207', label: 'Cổ Đại' },
    { slug: '/genre/doujinshi', label: 'Doujinshi' },
    { slug: '/genre/drama-103', label: 'Drama' },
    { slug: '/genre/dam-my', label: 'Đam Mỹ' },
    { slug: '/genre/ecchi', label: 'Ecchi' },
    { slug: '/genre/fantasy-1050', label: 'Fantasy' },
    { slug: '/genre/gender-bender-106', label: 'Gender Bender' },
    { slug: '/genre/harem-107', label: 'Harem' },
    { slug: '/genre/historical', label: 'Historical' },
    { slug: '/genre/horror', label: 'Horror' },
    { slug: '/genre/josei', label: 'Josei' },
    { slug: '/genre/live-action', label: 'Live action' },
    { slug: '/genre/manga-112', label: 'Manga' },
    { slug: '/genre/manhua', label: 'Manhua' },
    { slug: '/genre/manhwa-11400', label: 'Manhwa' },
    { slug: '/genre/martial-arts', label: 'Martial Arts' },
    { slug: '/genre/mature', label: 'Mature' },
    { slug: '/genre/mecha-117', label: 'Mecha' },
    { slug: '/genre/mystery', label: 'Mystery' },
    { slug: '/genre/ngon-tinh', label: 'Ngôn Tình' },
    { slug: '/genre/one-shot', label: 'One shot' },
    { slug: '/genre/psychological', label: 'Psychological' },
    { slug: '/genre/romance-121', label: 'Romance' },
    { slug: '/genre/school-life', label: 'School Life' },
    { slug: '/genre/sci-fi', label: 'Sci-fi' },
    { slug: '/genre/seinen', label: 'Seinen' },
    { slug: '/genre/shoujo', label: 'Shoujo' },
    { slug: '/genre/shoujo-ai-126', label: 'Shoujo Ai' },
    { slug: '/genre/shounen-127', label: 'Shounen' },
    { slug: '/genre/shounen-ai', label: 'Shounen Ai' },
    { slug: '/genre/slice-of-life', label: 'Slice of Life' },
    { slug: '/genre/smut', label: 'Smut' },
    { slug: '/genre/soft-yaoi', label: 'Soft Yaoi' },
    { slug: '/genre/soft-yuri', label: 'Soft Yuri' },
    { slug: '/genre/sports', label: 'Sports' },
    { slug: '/genre/supernatural', label: 'Supernatural' },
    { slug: '/genre/thieu-nhi', label: 'Thiếu Nhi' },
    { slug: '/genre/tragedy-136', label: 'Tragedy' },
    { slug: '/genre/trinh-tham', label: 'Trinh Thám' },
    { slug: '/genre/truyen-scan', label: 'Truyện scan' },
    { slug: '/genre/truyen-mau-214', label: 'Truyện Màu' },
    { slug: '/genre/webtoon', label: 'Webtoon' },
    { slug: '/genre/xuyen-khong-205', label: 'Xuyên Không' },
]

export default genres
